FROM amazoncorretto:17 AS jar-image
WORKDIR deploy
COPY build/libs/fibonacci_backend_cache-0.0.1.jar app.jar
RUN java -jar -Djarmode=layertools app.jar extract

FROM amazoncorretto:17
WORKDIR deploy
COPY --from=jar-image deploy/dependencies/ ./
COPY --from=jar-image deploy/snapshot-dependencies/ ./
COPY --from=jar-image deploy/spring-boot-loader/ ./
COPY --from=jar-image deploy/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]