apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- fibonacci-cache-namespace.yml
- fibonacci-cache-ingress.yml
- fibonacci-cache-config.yml
- fibonacci-cache-local-storage.yml
- fibonacci-cache-log-pvc.yml
- fibonacci-cache-deploy.yml
- fibonacci-cache-service.yml