kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80 # nginx-ingress 가 인식하는 포트
        hostPort: 80 # API 접속시 호스트 PC 의 80 포트로 접속
        protocol: TCP